# Day 2

Today, we will start using nf-core pipelines to find differentially abundant genes in our dataset. 
We are using data from the following paper: https://www.nature.com/articles/s41593-023-01350-3#Sec10

1. Please take some time to read through the paper and understand their approach, hypotheses and goals.

What was the objective of the study?

- Identify adaptations in mouse reward circuits associated with oxycodone physical dependence
- Reveal that chronic neuropathic pain states affect sensory, effective and molecular signatures of opioid withdrawl
- Demonstrate that treatment with HDAC1/HDAC2 inhibitor, Regenacy Brain Class 1 HDAC Inhibitor (RBC1HI), alleviates mechanical allodynia and prevents the expression of sensory and affective manifestations of oxycodone withdrawl, pointing to a new therapeutic approach for managment of chronic pain in opioid-dependent individuals.

What do the conditions mean?

**oxy**: reception of chronic oxycodone injections (treated group)


**sal**: saline injections (control group)

What do the genotypes mean?

**SNI**: spared nerve injury


**Sham**: control group

**Imagine you are the bioinformatician in the group who conducted this study. They hand you the raw files and ask you to analyze them.**

**What would you do?**

Frist of all, I would perform a quality control of the data. Then I would normalize the data that they hand out to me (for example y doing the log of every data that I have). Ideally, each data point would be labeled with some kind of ID, so I could differenciate from which condition each group is. Finally, I would perform a differential expression analysis of the different data points. 

**Which groups would you compare to each other?**

We have two conditions: the mouses that recieved a chronic oxycodone injection and the mouses that recieved a saline injection.

Then we also have two genotypes: SNI and Sham. 

Therefore, we would like to compare: SNI-oxy (treated group) vs SNI-sal (control group) and Sham-oxy (treated group) vs Sham-sal (control group) 

**Please also mention which outcome you would expect to see from each comparison.**

I would expect that genes might be significantly expressed in one of the conditions.

Your group gave you a very suboptimal excel sheet (conditions_runs_oxy_project.xlsx) to get the information you need for each run they uploaded to the SRA.<br>
So, instead of directly diving into downloading the data and starting the analysis, you first need to sort the lazy table.<br>
Use Python and Pandas to get the table into a more sensible order.<br>
Then, perform some overview analysis and plot the results
1. How many samples do you have per condition?
2. How many samples do you have per genotype?
3. How often do you have each condition per genotype?

In [1]:
import os
print(os.getcwd())

/home/paula/.ssh/computational-workflows-2026/day_02

In [1]:
import pandas as pd
import openpyxl

In [8]:
data = pd.read_excel("conditions_runs_oxy_project.xlsx")

data

,Patient,Run,RNA-seq,DNA-seq,condition: Sal,Condition: Oxy,Genotype: SNI,Genotype: Sham
0,?,SRR23195505,x,NaN,x,NaN,x,NaN
1,?,SRR23195506,x,NaN,NaN,x,NaN,x
2,?,SRR23195507,x,NaN,x,NaN,NaN,x
3,?,SRR23195508,x,NaN,NaN,x,x,NaN
4,?,SRR23195509,x,NaN,NaN,x,x,NaN
5,?,SRR23195510,x,NaN,x,NaN,x,NaN
6,?,SRR23195511,x,NaN,NaN,x,NaN,x
7,?,SRR23195512,x,NaN,x,NaN,NaN,x
8,?,SRR23195513,x,NaN,x,NaN,x,NaN
9,?,SRR23195514,x,NaN,NaN,x,NaN,x
10,?,SRR23195515,x,NaN,x,NaN,NaN,x
11,?,SRR23195516,x,NaN,NaN,x,x,NaN
12,?,SRR23195517,x,NaN,NaN,x,x,NaN
13,?,SRR23195518,x,NaN,x,NaN,x,NaN
14,?,SRR23195519,x,NaN,NaN,x,NaN,x
15,?,SRR23195520,x,NaN,x,NaN,NaN,x

**1. How many samples do you have per condition?**

There are a total of 8 measurments per condition

**2. How many samples do you have per genotype?**

There are a total of 8 samples per genotype (4 from Sal condition and 4 from Oxy condition)

**3. How often do you have each condition per genotype?**

Each condition is repeated 4 times per genotype

They were so kind to also provide you with the information of the number of bases per run, so that you can know how much space the data will take on your Cluster.<br>
Add a new column to your fancy table with this information (base_counts.csv) and sort your dataframe according to this information and the condition.

Then select the 2 smallest runs from your dataset and download them from SRA (maybe an nf-core pipeline can help here?...)

In [13]:
space = pd.read_csv("base_counts.csv")

space

            Run       Bases
0   SRR23195505  6922564500
1   SRR23195506  7859530800
2   SRR23195507  8063298900
3   SRR23195508  6927786900
4   SRR23195509  7003550100
5   SRR23195510  7377388500
6   SRR23195511  6456390900
7   SRR23195512  7462857900
8   SRR23195513  8099181600
9   SRR23195514  7226808600
10  SRR23195515  8169101700
11  SRR23195516  6203117700
12  SRR23195517  6863840400
13  SRR23195518  7908500400
14  SRR23195519  6996050100
15  SRR23195520  7858146000

In [16]:
data = data.merge(space, on="Run", how="left")
data

,Patient,Run,RNA-seq,DNA-seq,condition: Sal,Condition: Oxy,Genotype: SNI,Genotype: Sham,Bases_x,Bases_y
0,?,SRR23195505,x,NaN,x,NaN,x,NaN,6922564500,6922564500
1,?,SRR23195506,x,NaN,NaN,x,NaN,x,7859530800,7859530800
2,?,SRR23195507,x,NaN,x,NaN,NaN,x,8063298900,8063298900
3,?,SRR23195508,x,NaN,NaN,x,x,NaN,6927786900,6927786900
4,?,SRR23195509,x,NaN,NaN,x,x,NaN,7003550100,7003550100
5,?,SRR23195510,x,NaN,x,NaN,x,NaN,7377388500,7377388500
6,?,SRR23195511,x,NaN,NaN,x,NaN,x,6456390900,6456390900
7,?,SRR23195512,x,NaN,x,NaN,NaN,x,7462857900,7462857900
8,?,SRR23195513,x,NaN,x,NaN,x,NaN,8099181600,8099181600
9,?,SRR23195514,x,NaN,NaN,x,NaN,x,7226808600,7226808600
10,?,SRR23195515,x,NaN,x,NaN,NaN,x,8169101700,8169101700
11,?,SRR23195516,x,NaN,NaN,x,x,NaN,6203117700,6203117700
12,?,SRR23195517,x,NaN,NaN,x,x,NaN,6863840400,6863840400
13,?,SRR23195518,x,NaN,x,NaN,x,NaN,7908500400,7908500400
14,?,SRR23195519,x,NaN,NaN,x,NaN,x,6996050100,6996050100
15,?,SRR23195520,x,NaN,x,NaN,NaN,x,7858146000,7858146000

In [20]:
data = data.sort_values(by=["Bases_x"])
data

,Patient,Run,RNA-seq,DNA-seq,condition: Sal,Condition: Oxy,Genotype: SNI,Genotype: Sham,Bases_x,Bases_y
11,?,SRR23195516,x,NaN,NaN,x,x,NaN,6203117700,6203117700
6,?,SRR23195511,x,NaN,NaN,x,NaN,x,6456390900,6456390900
12,?,SRR23195517,x,NaN,NaN,x,x,NaN,6863840400,6863840400
0,?,SRR23195505,x,NaN,x,NaN,x,NaN,6922564500,6922564500
3,?,SRR23195508,x,NaN,NaN,x,x,NaN,6927786900,6927786900
14,?,SRR23195519,x,NaN,NaN,x,NaN,x,6996050100,6996050100
4,?,SRR23195509,x,NaN,NaN,x,x,NaN,7003550100,7003550100
9,?,SRR23195514,x,NaN,NaN,x,NaN,x,7226808600,7226808600
5,?,SRR23195510,x,NaN,x,NaN,x,NaN,7377388500,7377388500
7,?,SRR23195512,x,NaN,x,NaN,NaN,x,7462857900,7462857900
15,?,SRR23195520,x,NaN,x,NaN,NaN,x,7858146000,7858146000
1,?,SRR23195506,x,NaN,NaN,x,NaN,x,7859530800,7859530800
13,?,SRR23195518,x,NaN,x,NaN,x,NaN,7908500400,7908500400
2,?,SRR23195507,x,NaN,x,NaN,NaN,x,8063298900,8063298900
8,?,SRR23195513,x,NaN,x,NaN,x,NaN,8099181600,8099181600
10,?,SRR23195515,x,NaN,x,NaN,NaN,x,8169101700,8169101700

In [21]:
smallest_runs = data.nsmallest(2, "Bases_x")
smallest_runs

,Patient,Run,RNA-seq,DNA-seq,condition: Sal,Condition: Oxy,Genotype: SNI,Genotype: Sham,Bases_x,Bases_y
11,?,SRR23195516,x,NaN,NaN,x,x,NaN,6203117700,6203117700
6,?,SRR23195511,x,NaN,NaN,x,NaN,x,6456390900,6456390900

In [24]:
!nextflow run nf-core/fetchngs -r 1.13.0 -profile docker --input smallest_runs.csv --outdir fetchengs_results -c /home/paula/.ssh/computational-workflows-2026/nextflow.config

 N E X T F L O W   ~  version 26.04.6

Launching `https://github.com/nf-core/fetchngs` [suspicious_bassi] revision: 955c892d80 [1.13.0]

WARN: Unrecognized config option 'manifest.diagram'

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/fetchngs 1.13.0
------------------------------------------------------

Input/output options
  input              : smallest_runs.csv
  outdir             : fetchengs_results

Deprecated options
  trace_report_suffix: 2026-09-29_11-39-45

Core Nextflow options
  revision           : 1.13.0
  runName            : suspicious_bassi
  containerEngine    : docker
  launchDir          : /home/paula/.ssh/computational-workflows-2026/day_02
  workDir            : /home/paula/.ssh/computational-workflows-2026/day_02/work
  projectDir         : /home/paula/.nextflow/assets/.repos/nf-core/fetchngs/clones/955c892d80927cee633765e6e390f9cc6b7235c9
  userName           : paula
  profile            : docker
  configFiles        : /home/paula/.nextflow/assets/.repos/nf-core/fetchngs/clones/955c892d80927cee633765e6e390f9cc6b7235c9/nextflow.config, /home/paula/.ssh/computational-workflows-2026/nextflow.config

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------

* The pipeline
    https://doi.org/10.5281/zenodo.5070524

* The nf-core framework
    https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
    https://github.com/nf-core/fetchngs/blob/master/CITATIONS.md

[-        ] NFC…ETCHNGS:SRA_IDS_TO_RUNINFO -
[-        ] NFC…ETCHNGS:SRA_RUNINFO_TO_FTP -
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP -
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -

[-        ] NFC…ETCHNGS:SRA_IDS_TO_RUNINFO -
[-        ] NFC…ETCHNGS:SRA_RUNINFO_TO_FTP -
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP -
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

[-        ] NFC…ETCHNGS:SRA_IDS_TO_RUNINFO | 0 of 2
[-        ] NFC…ETCHNGS:SRA_RUNINFO_TO_FTP -
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP -
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/71/6a159dd67527e4f5c45c995e27dd9d71/6a159d]8;;] NFC…S_TO_RUNINFO (SRR23195511) | 0 of 2
[-        ] NFC…ETCHNGS:SRA_RUNINFO_TO_FTP -
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP -
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

executor >  local (2)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/71/6a159dd67527e4f5c45c995e27dd9d71/6a159d]8;;] NFC…S_TO_RUNINFO (SRR23195511) | 1 of 2
[-        ] NFC…ETCHNGS:SRA_RUNINFO_TO_FTP | 0 of 1
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP -
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

executor >  local (3)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/d1/44c0959bc7c615c44bc467db5d02dbd1/44c095]8;;] NFC…NINFO_TO_FTP (SRR23195511) | 0 of 2
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP -
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

executor >  local (3)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/d1/44c0959bc7c615c44bc467db5d02dbd1/44c095]8;;] NFC…NINFO_TO_FTP (SRR23195511) | 0 of 2
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP -
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

executor >  local (4)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/d1/44c0959bc7c615c44bc467db5d02dbd1/44c095]8;;] NFC…NINFO_TO_FTP (SRR23195511) | 1 of 2
[-        ] NFC…NGS:FETCHNGS:SRA_FASTQ_FTP | 0 of 1
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

executor >  local (5)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/85/81612c8b983952faede354aca6af8885/81612c]8;;] NFC… (SRX19144488_SRR23195511) | 0 of 2
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -

executor >  local (6)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/85/81612c8b983952faede354aca6af8885/81612c]8;;] NFC… (SRX19144488_SRR23195511) | 0 of 1, retries: 1
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)

executor >  local (6)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/85/81612c8b983952faede354aca6af8885/81612c]8;;] NFC… (SRX19144488_SRR23195511) | 0 of 2, retries: 1
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)

executor >  local (7)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/51/d05a7a700b1720851c9de45670919751/d05a7a]8;;] NFC… (SRX19144488_SRR23195511) | 0 of 2, retries: 2
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)
[d6/8aa9ce] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (1)

executor >  local (8)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/77/c549ea467a9dba4168bf8ef2ccb55b77/c549ea]8;;] NFC… (SRX19144486_SRR23195516) | 0 of 2, retries: 3
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)
[d6/8aa9ce] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (1)
[51/d05a7a] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (2)

executor >  local (8)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/77/c549ea467a9dba4168bf8ef2ccb55b77/c549ea]8;;] NFC… (SRX19144486_SRR23195516) | 0 of 2, retries: 3
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)
[d6/8aa9ce] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (1)
[51/d05a7a] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (2)

executor >  local (9)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/b0/68811ede069221bafe4cd57ba5fc96b0/68811e]8;;] NFC… (SRX19144488_SRR23195511) | 0 of 2, retries: 4
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)
[d6/8aa9ce] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (1)
[51/d05a7a] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (2)
[77/c549ea] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (2)

executor >  local (10)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/47/14c3f378f8683a81902e60deae3be647/14c3f3]8;;] NFC… (SRX19144486_SRR23195516) | 0 of 2, retries: 4
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)
[d6/8aa9ce] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (1)
[51/d05a7a] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (2)
[77/c549ea] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (2)
ERROR ~ Error executing process > 'NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)'

Caused by:
  Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8)


Command executed:

  wget \
      -t 5 -nv -w 5 --random-wait -c -T 60 \
      -O SRX19144488_SRR23195511_1.fastq.gz \
      ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_1.fastq.gz

  echo "337b9e2d8292d8a29a36bdb1dc80cca5  SRX19144488_SRR23195511_1.fastq.gz" > SRX19144488_SRR23195511_1.fastq.gz.md5
  md5sum -c SRX19144488_SRR23195511_1.fastq.gz.md5

  wget \
      -t 5 -nv -w 5 --random-wait -c -T 60 \
      -O SRX19144488_SRR23195511_2.fastq.gz \
      ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_2.fastq.gz

  echo "9a7c146f7304e9c8851a14fcb2795512  SRX19144488_SRR23195511_2.fastq.gz" > SRX19144488_SRR23195511_2.fastq.gz.md5
  md5sum -c SRX19144488_SRR23195511_2.fastq.gz.md5

Command exit status:
  8

Command output:
  (empty)

Command error:
  Prepended http:// to 'ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_1.fastq.gz'
  http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_1.fastq.gz:
  2026-09-29 11:04:39 ERROR 403: Forbidden.

Work dir:
  /home/paula/.ssh/computational-workflows-2026/day_02/work/b0/68811ede069221bafe4cd57ba5fc96

Container:
  community.wave.seqera.io/library/gzip_wget:041a8ba200c3fa3f

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

executor >  local (10)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/bc/f4c845436f02975d13fb3d2d8fa438bc/f4c845]8;;] NFC…S_TO_RUNINFO (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/a9/8a1969ac0435471e9308276e80ace8a9/8a1969]8;;] NFC…NINFO_TO_FTP (SRR23195516) | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_02/work/b0/68811ede069221bafe4cd57ba5fc96b0/68811e]8;;] NFC… (SRX19144488_SRR23195511) | 0 of 2, retries: 4
[-        ] NFC…USTOM_SRATOOLSNCBISETTINGS -
[-        ] NFC…SRATOOLS:SRATOOLS_PREFETCH -
[-        ] NFC…TOOLS:SRATOOLS_FASTERQDUMP -
[-        ] NFC…TCHNGS:FETCHNGS:ASPERA_CLI -
[-        ] NFC…_FETCHNGS:FETCHNGS:FASTQDL -
[-        ] NFC…GS:MULTIQC_MAPPINGS_CONFIG -
[85/81612c] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (1)
[d6/8aa9ce] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (1)
[51/d05a7a] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8) -- Execution is retried (2)
[77/c549ea] NOTE: Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144486_SRR23195516)` terminated with an error exit status (8) -- Execution is retried (2)
ERROR ~ Error executing process > 'NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)'

Caused by:
  Process `NFCORE_FETCHNGS:FETCHNGS:SRA_FASTQ_FTP (SRX19144488_SRR23195511)` terminated with an error exit status (8)


Command executed:

  wget \
      -t 5 -nv -w 5 --random-wait -c -T 60 \
      -O SRX19144488_SRR23195511_1.fastq.gz \
      ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_1.fastq.gz

  echo "337b9e2d8292d8a29a36bdb1dc80cca5  SRX19144488_SRR23195511_1.fastq.gz" > SRX19144488_SRR23195511_1.fastq.gz.md5
  md5sum -c SRX19144488_SRR23195511_1.fastq.gz.md5

  wget \
      -t 5 -nv -w 5 --random-wait -c -T 60 \
      -O SRX19144488_SRR23195511_2.fastq.gz \
      ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_2.fastq.gz

  echo "9a7c146f7304e9c8851a14fcb2795512  SRX19144488_SRR23195511_2.fastq.gz" > SRX19144488_SRR23195511_2.fastq.gz.md5
  md5sum -c SRX19144488_SRR23195511_2.fastq.gz.md5

Command exit status:
  8

Command output:
  (empty)

Command error:
  Prepended http:// to 'ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_1.fastq.gz'
  http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR231/011/SRR23195511/SRR23195511_1.fastq.gz:
  2026-09-29 11:04:39 ERROR 403: Forbidden.

Work dir:
  /home/paula/.ssh/computational-workflows-2026/day_02/work/b0/68811ede069221bafe4cd57ba5fc96

Container:
  community.wave.seqera.io/library/gzip_wget:041a8ba200c3fa3f

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

executor >  local (10)

We have 4 files: it's 2 per sample (one forward and one reverse)

While your files are downloading, get back to the paper and explain how you would try to reproduce the analysis.<br>
When you are done with this shout, so we can discuss the different ideas.

To reproduce the analysis, I would first download the raw RNA-seq data from SRA. Then I, would perform quality control on the FASTAQ files and align the reads to the mouse reference genome. After the alignment step, I would quantify the number of reads to each gene and create a gene count matrix.

Next, I would use the sample metadata to define the experimental groups (genotype SNI and Sham, and condition oxy and sal). I would then perform differential gene expression analysis, using DESeq2 (the same that they used in the paper). Therefore I'm following a similar design to the one described in the paper.

Finally, I would compare the different experimental groups, identify differentially expressed genes and reproduce some of the figures. If possible, I would also perform pathway or Gene Ontology analysis to compare the biological results with those reported in the paper.