# Nextflow Basics: Introduction to channels and operators

Today, we will begin exploring Nextflow, the programming language that powers the advanced nf-core pipelines you worked with the past days. Your task is to dive into the core concepts and syntax of Nextflow, understanding how this language enables the development of scalable and reproducible workflows.

Nextflow works quite differently from traditional programming languages like Python or Java that you may already be familiar with. To get started, it is essential to understand the foundational concepts that set Nextflow apart.

### 1. Describe the concept of Workflows, Processes and Channels we deal with in Nextflow

**Workflows**: a specialized function for composing processes and dataflow logic:
* An entry workflow is the entrypoint of a pipeline. It can take parameters as inputs using the params block, and it can publish outputs using the output block
* A named workflow is a workflow that can be called by other workflows. It can define its own inputs and outputs, which are called takes and emits.

Both entry workflows and named workflows con contain dataflow logic such as calling processes, workflows, and channel operators.





**Processes**: a specialized function for executing scripts in a scalable and portable manner. 






**Channels**: asynchronous data queues that connect independent processes and enable parallel execution in a pipeline. in other words, they are queues designed to handle inputs efficiently and shuttle them from one step to another in multi-step workflows, while providing built-in parallelism and many additional benefits.

## **Introduction to channels**

Please refer to the file  $\texttt{channels\_intro.nf}$ for the next exercises. Then run the code with the respective flag here below.

In [2]:
# Task 1 - Create a channel that enumerates the numbers from 1 to 10
!nextflow run channels_intro.nf --step 1

 N E X T F L O W   ~  version 26.04.6

Launching `channels_intro.nf` [tender_elion] revision: 3db4b5eda9

1
2
3
4
5
6
7
8
9
10

In [4]:
# Task 2 - Create a channel that gives out the entire alphabet
!nextflow run channels_intro.nf --step 2

 N E X T F L O W   ~  version 26.04.6

Launching `channels_intro.nf` [cranky_bassi] revision: b3cfb08f09

A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z

In [5]:
# Task 3 - Create a channel that includes all files in the "files_dir" directory
!nextflow run channels_intro.nf --step 3

 N E X T F L O W   ~  version 26.04.6

Launching `channels_intro.nf` [nice_woese] revision: 4ddee82ba5

/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR2_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR1_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR4_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR3_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR3_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq1_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq3_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR4_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq3_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_1.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR5_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR5_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq2_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq4_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_3.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_4.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_5.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq4_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq2_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq5_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_2.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq5_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq1_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR1_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR2_2.fq

In [7]:
# Task 4 - Create a channel that includes all TXT files in the "files_dir" directory
!nextflow run channels_intro.nf --step 4

 N E X T F L O W   ~  version 26.04.6

Launching `channels_intro.nf` [fabulous_raman] revision: e1ef54099b

/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_1.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_3.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_4.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_5.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_2.txt

In [8]:
# Task 5 - Create a channel that includes the files "fastq_1.fq" and "fastq_2.fq" in the "files_dir" directory
!nextflow run channels_intro.nf --step 5

 N E X T F L O W   ~  version 26.04.6

Launching `channels_intro.nf` [lonely_jang] revision: aaa198c697

/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_2.fq

In [9]:
# Task 6 - go back to the time when you included all files. Are you sure that really ALL files are included? If not, how can you include them?
!nextflow run channels_intro.nf --step 6

 N E X T F L O W   ~  version 26.04.6

Launching `channels_intro.nf` [maniac_bardeen] revision: b5c6ed4741

/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR2_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR1_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR4_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR3_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR3_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq1_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq3_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR4_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq3_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_1.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR5_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR5_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq2_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq4_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_3.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_4.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_5.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq4_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/.hidden_2.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq2_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq5_2.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_2.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/.hidden_1.txt
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq5_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq1_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR1_1.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq.fq
/home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR2_2.fq

In [13]:
# Task 7 - get all filepairs in the "files_dir" directory
!nextflow run channels_intro.nf --step 7

 N E X T F L O W   ~  version 26.04.6

Launching `channels_intro.nf` [shrivelled_carson] revision: ccadeae7a7

[SRR3, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR3_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR3_2.fq]
[SRR4, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR4_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR4_2.fq]
[fastq3, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq3_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq3_2.fq]
[SRR5, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR5_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR5_2.fq]
[fastq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq_2.fq]
[fastq4, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq4_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq4_2.fq]
[fastq2, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq2_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq2_2.fq]
[file, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_1.txt, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/file_2.txt]
[fastq5, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq5_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq5_2.fq]
[fastq1, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq1_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/fastq1_2.fq]
[SRR1, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR1_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR1_2.fq]
[SRR2, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR2_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR2_2.fq]

## Now that you have a solid understanding of the basic concepts of channels in Nextflow, it’s time to experiment and see how they work in practice.

To do so, Nextflow has the concept of Operators to give and pass information inbetween channels.

Please answer the questions in $\texttt{basic\_channel\_operations.nf}$ and run the code here.

operator webpage: https://docs.seqera.io/nextflow/reference/operator

In [15]:
# Task 1 - Extract the first item from the channel
!nextflow run basic_channel_operations.nf --step 1

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [irreverent_pesquet] revision: 194e762625

1

In [16]:
# Task 2 - Extract the last item from the channel
!nextflow run basic_channel_operations.nf --step 2

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [ecstatic_kay] revision: 3e53316d45

3

In [17]:
# Task 3 - Use an operator to extract the first two items from the channel
!nextflow run basic_channel_operations.nf --step 3

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [mighty_wegener] revision: 0383c91f94

1
2

In [18]:
# Task 4 - Return the squared values of the channel
!nextflow run basic_channel_operations.nf --step 4

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [focused_faraday] revision: 15ecffaaf5

4
9
16

In [19]:
# Task 5 - Remember the previous task where you squared the values of the channel. Now, extract the first two items from the squared channel
!nextflow run basic_channel_operations.nf --step 5

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [happy_ardinghelli] revision: 15ecffaaf5

4
9

In [20]:
# Task 6 - Remember when you used bash to reverse the output? Try to use map and Groovy to reverse the output
!nextflow run basic_channel_operations.nf --step 6

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [evil_edison] revision: 67f87557e8

rolyaT
tfiwS

In [23]:
# Task 7 - Use fromPath to include all fastq files in the "files_dir" directory, then use map to return a pair containing the file name and the file path (Hint: include groovy code)
!nextflow run basic_channel_operations.nf --step 7

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [extravagant_nobel] revision: 5d7c1fd7b8

[SRR2_1.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR2_1.fq]
[SRR.fq, /home/paula/.ssh/computational-workflows-2026/day_05/files_dir/SRR.fq]

In [24]:
# Task 8 - Combine the items from the two channels into a single channel
!nextflow run basic_channel_operations.nf --step 8

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [loving_mirzakhani] revision: 53037a82a5

1
2
3
4
5
6

In [25]:
# Task 9 - Flatten the list in the channel
!nextflow run basic_channel_operations.nf --step 9

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [modest_franklin] revision: 193979b753

1
2
3
4
5
6

In [26]:
# Task 10 - Collect the items of a channel into a list. What kind of channel is the output channel?
!nextflow run basic_channel_operations.nf --step 10

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [crazy_yonath] revision: 816a6d16de

[1, 2, 3]

**What kind of channel is the output channel?**

The outpit is a dataflow value (COMPLETAR)

In [27]:
# Task 11 -  From the input channel, create lists where each first item in the list of lists is the first item in the output channel, followed by a list of all the items its paired with
!nextflow run basic_channel_operations.nf --step 11

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [nostalgic_bell] revision: 2aebcb7d6c

[1, [V, f, B]]
[3, [M, G, 33]]
[2, [O, L, E]]

In [28]:
# Task 12 - Create a channel that joins the input to the output channel. What do you notice?
!nextflow run basic_channel_operations.nf --step 12

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [nasty_feynman] revision: 2efa0c5536

[1, V, f]
[3, M, G]
[2, O, L]

**Task 12 - What do you notice compared to Task 11?**

In Task 11, ` groupTuple() ` groups all values that have the same key into a list. For example, several pairs starting with `1` are grouped into one output like `[1, [V, f, B]]`.

In Task 12, `join()` combines items from two different channels that share the same key. The reuslt contains the key, the value from the left channel, and the matching value from the right channel, for example `[1, V, f]`.

So, `groupTuple()` groups values, while `join()` matches values between channels.

In [29]:
# Task 13 - Split the input channel into two channels, one of all the even numbers and the other of all the odd numbers.
#           Write them to stdout including information about which is which
!nextflow run basic_channel_operations.nf --step 13 -dump-channels

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [drunk_sanger] revision: 2eac591fb3

Even numbers: [2, 4, 6, 8, 10]
Odd numbers: [1, 3, 5, 7, 9]

In [30]:
# Task 14 - Nextflow has the concept of maps. Write the names in the maps in this channel to a file called "names.txt". Each name should be on a new line. 
#           Store the file in the "results" directory under the name "names.txt"

!nextflow run basic_channel_operations.nf --step 14

!cat results/names.txt

 N E X T F L O W   ~  version 26.04.6

Launching `basic_channel_operations.nf` [loving_spence] revision: 09846eb1e0

Snape
Albus
Ron
Hagrid
Dobby
Hermione
Harry

## Now that we learned about Channels and Operators to deal with them, let's focus on Processes that make use of these channels.

Please answer the questions in $\texttt{basics\_processes.nf}$ and run the code here.

In [5]:
# Task 1 - create a process that says Hello World! (add debug true to the process right after initializing to be sable to print the output to the console)
!nextflow run basics_processes.nf --step 1

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [voluminous_moriondo] revision: 06d0cca2a0

[-        ] SAYHELLO -

[-        ] SAYHELLO | 0 of 1

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/63/a741bf9f904dc16471f5233aff1f3b63/a741bf]8;;] SAYHELLO | 1 of 1 ✔
Hello World!

In [8]:
# Task 2 - create a process that says Hello World! using Python
!nextflow run basics_processes.nf --step 2

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [scruffy_raman] revision: 0c47c6e7df

[-        ] SAYHELLO_PYTHON -

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/23/7ce79bfa3f8dae48750c6d913dfd4323/7ce79b]8;;] SAYHELLO_PYTHON | 0 of 1
Hello World!


executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/23/7ce79bfa3f8dae48750c6d913dfd4323/7ce79b]8;;] SAYHELLO_PYTHON | 1 of 1 ✔
Hello World!

In [12]:
# Task 3 - create a process that reads in the string "Hello world!" from a channel and write it to command line
!nextflow run basics_processes.nf --step 3

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [loving_pauling] revision: c5ce46d134

[-        ] SAYHELLO_PARAM -

[-        ] SAYHELLO_PARAM | 0 of 1

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ed/5eb76342f557fe672577e75d6c9afeed/5eb763]8;;] SAYHELLO_PARAM (1) | 0 of 1 ✔

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ed/5eb76342f557fe672577e75d6c9afeed/5eb763]8;;] SAYHELLO_PARAM (1) | 1 of 1 ✔

In [13]:
# Task 4 - create a process that reads in the string "Hello world!" from a channel and write it to a file. 
!nextflow run basics_processes.nf --step 4

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [elated_bose] revision: c5ce46d134

[-        ] SAYHELLO_FILE -

[-        ] SAYHELLO_FILE | 0 of 1

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/02/f33ac934192d7a1855b7d4c55be93f02/f33ac9]8;;] SAYHELLO_FILE (1) | 1 of 1 ✔
Hello world!

**It might be that you created the file but it doesnt appear in the directory. Use the work folder and the output on the command line to find the file.**

In [14]:
# Task 5 - create a process that reads in a string and converts it to uppercase and saves it to a file as output. View the path to the file in the console
!nextflow run basics_processes.nf --step 5

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [friendly_allen] revision: c5ce46d134

[-        ] UPPERCASE -

[-        ] UPPERCASE | 0 of 1

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/d5/a1aa4732423081f883c47e4b43b6b0d5/a1aa47]8;;] UPPERCASE (1) | 1 of 1 ✔
/home/paula/.ssh/computational-workflows-2026/day_05/work/d5/a1aa4732423081f883c47e4b43b6b0/uppercase.txt

In [15]:
# Task 6 - add another process that reads in the resulting file from UPPERCASE and print the content to the console (debug true).
!nextflow run basics_processes.nf --step 6

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [tender_bhaskara] revision: c5ce46d134

[-        ] UPPERCASE  -
[-        ] PRINTUPPER -

[-        ] UPPERCASE  | 0 of 1
[-        ] PRINTUPPER -

executor >  local (2)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/68/17a87be26a7b9b98173de095392b9968/17a87b]8;;] UPPERCASE (1)  | 1 of 1 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/4e/6f1db4a98116526e4d2fdf46879b2d4e/6f1db4]8;;] PRINTUPPER (1) | 0 of 1

executor >  local (2)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/68/17a87be26a7b9b98173de095392b9968/17a87b]8;;] UPPERCASE (1)  | 1 of 1 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/4e/6f1db4a98116526e4d2fdf46879b2d4e/6f1db4]8;;] PRINTUPPER (1) | 1 of 1 ✔
HELLO WORLD!

Comared to all the other runs. What changed in the output here and why?

In [1]:
# Task 7 - based on the paramater "zip" (see at the head of the file), create a process that zips the file created in the UPPERCASE process either in "zip", "gzip" OR "bzip2" format.
#          Print out the path to the zipped file in the console
!nextflow run basics_processes.nf --step 7

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [nasty_ekeblad] revision: c5ce46d134

[-        ] UPPERCASE -
[-        ] COMPRESS  -

[-        ] UPPERCASE | 0 of 1
[-        ] COMPRESS  -

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/fb/dee5869a566fd95a9c84039fdf6a39fb/dee586]8;;] UPPERCASE (1) | 0 of 1
[-        ] COMPRESS      -

executor >  local (2)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/fb/dee5869a566fd95a9c84039fdf6a39fb/dee586]8;;] UPPERCASE (1) | 1 of 1 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/50/72d8811cb36f8cc1d2904679f5c92150/72d881]8;;] COMPRESS (1)  | 1 of 1 ✔
/home/paula/.ssh/computational-workflows-2026/day_05/work/50/72d8811cb36f8cc1d2904679f5c921/uppercase.txt.zip

executor >  local (2)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/fb/dee5869a566fd95a9c84039fdf6a39fb/dee586]8;;] UPPERCASE (1) | 1 of 1 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/50/72d8811cb36f8cc1d2904679f5c92150/72d881]8;;] COMPRESS (1)  | 1 of 1 ✔
/home/paula/.ssh/computational-workflows-2026/day_05/work/50/72d8811cb36f8cc1d2904679f5c921/uppercase.txt.zip

In [8]:
# Task 8 - Create a process that zips the file created in the UPPERCASE process in "zip", "gzip" AND "bzip2" format. Print out the paths to the zipped files in the console
!nextflow run basics_processes.nf --step 8

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [pedantic_leibniz] revision: 9249dc6841

[-        ] UPPERCASE -
[-        ] COMPRESS  -

[-        ] UPPERCASE | 0 of 1
[-        ] COMPRESS  -

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ea/8368caf1754efc891e24527136ab17ea/8368ca]8;;] UPPERCASE (1) | 0 of 1
[-        ] COMPRESS      -

executor >  local (4)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ea/8368caf1754efc891e24527136ab17ea/8368ca]8;;] UPPERCASE (1) | 1 of 1 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/44/49d5d1b3fcf16109ca432e3efb1e5244/49d5d1]8;;] COMPRESS (2)  | 1 of 3
/home/paula/.ssh/computational-workflows-2026/day_05/work/44/49d5d1b3fcf16109ca432e3efb1e52/compressed_gzip.gz
/home/paula/.ssh/computational-workflows-2026/day_05/work/af/1d3be816eca4388b28ff442f543857/compressed_bzip2.bz2

executor >  local (4)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ea/8368caf1754efc891e24527136ab17ea/8368ca]8;;] UPPERCASE (1) | 1 of 1 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/76/a00c9e4c472b9aadf11e6cbb0d3a3776/a00c9e]8;;] COMPRESS (1)  | 3 of 3 ✔
/home/paula/.ssh/computational-workflows-2026/day_05/work/44/49d5d1b3fcf16109ca432e3efb1e52/compressed_gzip.gz
/home/paula/.ssh/computational-workflows-2026/day_05/work/af/1d3be816eca4388b28ff442f543857/compressed_bzip2.bz2
/home/paula/.ssh/computational-workflows-2026/day_05/work/76/a00c9e4c472b9aadf11e6cbb0d3a37/compressed_zip.zip

In [10]:
 # Task 9 - Create a process that reads in a list of names and titles from a channel and writes them to a file.
#           Store the file in the "results" directory under the name "names.tsv"
!nextflow run basics_processes.nf --step 9

 N E X T F L O W   ~  version 26.04.6

Launching `basics_processes.nf` [spontaneous_chandrasekhar] revision: c97e66e400

[-        ] WRITETOFILE -

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/db/0c6b004b25a53126fbac015530eca4db/0c6b00]8;;] WRITETOFILE | 0 of 1

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/db/0c6b004b25a53126fbac015530eca4db/0c6b00]8;;] WRITETOFILE | 0 of 1 ✔

executor >  local (1)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/db/0c6b004b25a53126fbac015530eca4db/0c6b00]8;;] WRITETOFILE | 1 of 1 ✔

In [11]:
import pandas as pd

df = pd.read_csv("results/names.tsv", sep="\t")
df

      Harry       student
0       Ron       student
1  Hermione       student
2     Albus    headmaster
3     Snape       teacher
4    Hagrid  groundkeeper
5     Dobby          hero

## Now, let's try some more advanced Operators

Please answer the questions in $\texttt{advanced\_channel\_operations.nf}$ and run the code here.

To come closer to actual pipelines, we introduce the concept of "meta-maps" which you can imagine as dictionaries that are passed with data via channels containing crucial metadata on the sample. 

Also, we will come back to samplesheets which from the past days.

In [12]:
# Task 1 - Read in the samplesheet.

!nextflow run advanced_channel_operations.nf --step 1

 N E X T F L O W   ~  version 26.04.6

Launching `advanced_channel_operations.nf` [drunk_boltzmann] revision: ab98fc7849

[sample:CONTROL_REP1, fastq_1:fq_1_R1.fastq.gz, fastq_2:fq_1_R2.fastq.gz, strandedness:auto]
[sample:CONTROL_REP2, fastq_1:fq_2_R1.fastq.gz, fastq_2:fq_2_R2.fastq.gz, strandedness:forward]
[sample:CONTROL_REP3, fastq_1:fq_3_R1.fastq.gz, fastq_2:fq_3_R2.fastq.gz, strandedness:reverse]
[sample:CONTROL_REP1, fastq_1:fq_4_R1.fastq.gz, fastq_2:fq_4_R2.fastq.gz, strandedness:auto]

In [22]:
import pandas as pd

x = pd.read_csv("/home/paula/.ssh/computational-workflows-2026/day_05/samplesheet.csv")
x

         sample           fastq_1           fastq_2 strandedness
0  CONTROL_REP1  fq_1_R1.fastq.gz  fq_1_R2.fastq.gz         auto
1  CONTROL_REP2  fq_2_R1.fastq.gz  fq_2_R2.fastq.gz      forward
2  CONTROL_REP3  fq_3_R1.fastq.gz  fq_3_R2.fastq.gz      reverse
3  CONTROL_REP1  fq_4_R1.fastq.gz  fq_4_R2.fastq.gz         auto

In [23]:
# Task 2 - Read in the samplesheet and create a meta-map with all metadata and another list with the filenames ([[metadata_1 : metadata_1, ...], [fastq_1, fastq_2]]).
#          Set the output to a new channel "in_ch" and view the channel. YOU WILL NEED TO COPY AND PASTE THIS CODE INTO SOME OF THE FOLLOWING TASKS (sorry for that).

!nextflow run advanced_channel_operations.nf --step 2

 N E X T F L O W   ~  version 26.04.6

Launching `advanced_channel_operations.nf` [goofy_torvalds] revision: 06ad14f1f9

[[sample:CONTROL_REP1, strandedness:auto], [fq_1_R1.fastq.gz, fq_1_R2.fastq.gz]]
[[sample:CONTROL_REP2, strandedness:forward], [fq_2_R1.fastq.gz, fq_2_R2.fastq.gz]]
[[sample:CONTROL_REP3, strandedness:reverse], [fq_3_R1.fastq.gz, fq_3_R2.fastq.gz]]
[[sample:CONTROL_REP1, strandedness:auto], [fq_4_R1.fastq.gz, fq_4_R2.fastq.gz]]

In [24]:
# Task 3 - Now we assume that we want to handle different "strandedness" values differently. 
#          Split the channel into the right amount of channels and write them all to stdout so that we can understand which is which.

!nextflow run advanced_channel_operations.nf --step 3 -dump-channels

 N E X T F L O W   ~  version 26.04.6

Launching `advanced_channel_operations.nf` [wise_shockley] revision: d7f9600265

AUTO: [[sample:CONTROL_REP1, strandedness:auto], [fq_1_R1.fastq.gz, fq_1_R2.fastq.gz]]
FORWARD: [[sample:CONTROL_REP2, strandedness:forward], [fq_2_R1.fastq.gz, fq_2_R2.fastq.gz]]
REVERSE: [[sample:CONTROL_REP3, strandedness:reverse], [fq_3_R1.fastq.gz, fq_3_R2.fastq.gz]]
AUTO: [[sample:CONTROL_REP1, strandedness:auto], [fq_4_R1.fastq.gz, fq_4_R2.fastq.gz]]

In [25]:
# Task 4 - Group together all files with the same sample-id and strandedness value.

!nextflow run advanced_channel_operations.nf --step 4

 N E X T F L O W   ~  version 26.04.6

Launching `advanced_channel_operations.nf` [zen_ochoa] revision: 169f7878c5

[CONTROL_REP1, [auto, auto], [[fq_1_R1.fastq.gz, fq_1_R2.fastq.gz], [fq_4_R1.fastq.gz, fq_4_R2.fastq.gz]]]
[CONTROL_REP2, [forward], [[fq_2_R1.fastq.gz, fq_2_R2.fastq.gz]]]
[CONTROL_REP3, [reverse], [[fq_3_R1.fastq.gz, fq_3_R2.fastq.gz]]]

## It's finally time to link processes and channels with each other

Please go to the file $\texttt{link\_p\_c.nf}$

In [28]:
import pandas as pd

y = pd.read_csv("/home/paula/.ssh/computational-workflows-2026/day_05/samplesheet_2.csv")
y

   block_size                input_str out_name
0           4              Hello World      h_w
1           3  Computational Workflows      c_w

In [34]:
!nextflow run link_p_c.nf

 N E X T F L O W   ~  version 26.04.6

Launching `link_p_c.nf` [small_meucci] revision: 9d8fb42adf

[-        ] SPLITLETTERS   -
[-        ] CONVERTTOUPPER -

executor >  local (2)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/1c/86d96af6679afdd72b53a7f3a408d81c/86d96a]8;;] SPLITLETTERS (1) | 1 of 2 ✔
[-        ] CONVERTTOUPPER   -

executor >  local (6)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ac/0026ffdca4b542bbccc9eaea81236fac/0026ff]8;;] SPLITLETTERS (2)   | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/2f/fc992b299b35e7e71eb6975d88e9df2f/fc992b]8;;] CONVERTTOUPPER (1) | 0 of 11

executor >  local (13)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ac/0026ffdca4b542bbccc9eaea81236fac/0026ff]8;;] SPLITLETTERS (2)    | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/5a/a641b66859af8c05bae4250a89da825a/a641b6]8;;] CONVERTTOUPPER (11) | 11 of 11 ✔

executor >  local (13)
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/ac/0026ffdca4b542bbccc9eaea81236fac/0026ff]8;;] SPLITLETTERS (2)    | 2 of 2 ✔
[]8;;file:///home/paula/.ssh/computational-workflows-2026/day_05/work/5a/a641b66859af8c05bae4250a89da825a/a641b6]8;;] CONVERTTOUPPER (11) | 11 of 11 ✔

### Give a list with the paths to the chunk files

### Why was CONVERTTOUPPER run so often?